import matplotlib.pyplot as plt
import numpy as np
np.random.seed(2000)
y = np.random.standard_normal((20 , 2)).cumsum(axis=0)

plt.figure(figsize= (9 ,4))
plt.subplot(211)
plt.plot(y[: , 0] , lw = 5 , label = '1st')
plt.plot(y[:, 0] , 'ro')
plt.grid(True)
plt.legend(loc= 0)
plt.axis('tight')
plt.ylabel('value')
plt.title('A Simple Plot')
plt.subplot(212)
plt.plot(y[: , 1] ,'g', lw = 5 , label = '2nd')
plt.plot(y[: , 1] , 'ro')
plt.grid(True)
plt.legend(loc= 0)
plt.axis('tight')
plt.xlabel('index')
plt.ylabel('value')
plt.title('A Simple Plot')
plt.show()